# SPDX-FileCopyrightText: 2024 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "Envoy"
SPDX-PackageSupplier = "Igor Cota <hello@foundation.xyz>"
SPDX-PackageDownloadLocation = "https://github.com/Foundation-Devices/envoy"

[[annotations]]
path = "assets/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "lib/l10n/**.arb"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "ios/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "linux/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "web/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "macos/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "android/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "google_fonts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ".**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**/.DS_Store"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**/.idea/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "lib/business/**.g.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "test/**.mocks.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "packages/wallet/lib/**.g.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "packages/wallet/lib/generated_bindings.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "packages/ur/lib/generated_bindings.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "packages/http_tor/lib/generated_bindings.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "packages/backup/lib/generated_bindings.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "lib/generated/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "lib/business/**.freezed.**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "packages/wallet/lib/**.freezed.**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "test/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "integration_test/assets/beefqa_backup.mla.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "test/assets/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "lib/account/legacy/legacy_account.g.dart"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Foundation Devices Inc."
SPDX-License-Identifier = "GPL-3.0-or-later"