# SPDX-FileCopyrightText: 2025 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later


[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-analyzer"]
targets = ["aarch64-apple-ios", "aarch64-apple-darwin", "aarch64-linux-android", "x86_64-linux-android"]
