# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-linux-android]
linker = "aarch64-linux-android30-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android30-clang"

[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-target", "-C", "link-arg=arm64-apple-ios14.0"]

[net]
git-fetch-with-cli = true