# SPDX-FileCopyrightText: 2025 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "rust_lib_http_tor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
reqwest = { version = "0.12.23", features = ["socks", "blocking"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4"
anyhow = "1.0"
log = "0.4.27"
openssl = { version = "0.10", features = ["vendored"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
