# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "tor-ffi"
version = "0.1.0"
authors = ["Igor Cota <igor@foundationdevices.com>"]
edition = "2018"

[lib]
name = "tor_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
lazy_static = "1.4"
tokio = { version = "1", features = ["full"] }
arti-client = { version = "0.10.0", features = ["static"] }
arti = { version = "1.1.6", features = ["experimental-api", "static"] }
tor-rtcompat = { version = "0.9.2", features = ["static"] }
tempfile = "3.7.1"
#android_log-sys = "0.3.1"

[build-dependencies]
cbindgen = "= 0.24.3"
